# Generated by Django 5.2.9 on 2025-12-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: TVA Standard', max_length=50, verbose_name='Nom de la taxe')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux (%)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Taux par défaut')),
            ],
            options={
                'verbose_name': 'Taux de TVA',
                'verbose_name_plural': 'Taux de TVA',
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de TVA Intracom.')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='SIRET / Registration ID')),
                ('legal_mention', models.TextField(blank=True, help_text='Ex: SARL au capital de...', verbose_name='Mentions légales (Pied de facture)')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('zip_code', models.CharField(max_length=20, verbose_name='Code Postal')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('currency_symbol', models.CharField(default='€', max_length=5, verbose_name='Symbole Monétaire')),
                ('default_tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.taxrate', verbose_name='Taxe par défaut')),
            ],
            options={
                'verbose_name': 'Paramètres Entreprise',
                'verbose_name_plural': 'Paramètres Entreprise',
            },
        ),
    ]
