# Generated by Django 5.2.9 on 2025-12-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat HT")),
                ('lead_time_days', models.PositiveIntegerField(default=0, verbose_name='Délai de livraison (jours)')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='Fournisseur principal ?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_prices', to='inventory.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.supplier')),
            ],
            options={
                'verbose_name': 'Prix Fournisseur',
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
