# Generated by Django 5.2.9 on 2025-12-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierprice',
            options={'verbose_name': 'Prix Fournisseur', 'verbose_name_plural': 'Prix Fournisseurs'},
        ),
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.CharField(default='€', max_length=5, verbose_name="Devise d'achat"),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='Ex: 30 jours fin de mois', max_length=100, verbose_name='Conditions de paiement'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='SIRET / ID Légal'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° TVA Intracom.'),
        ),
        migrations.AddField(
            model_name='supplierprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du fournisseur'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Remise (%)'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name="Quantité mini d'achat"),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='procurement.supplier'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='valid_from',
            field=models.DateField(verbose_name='Valide du'),
        ),
        migrations.AlterField(
            model_name='supplieroffer',
            name='valid_until',
            field=models.DateField(verbose_name='Valide au'),
        ),
        migrations.AlterField(
            model_name='supplierprice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_supplied', to='procurement.supplier'),
        ),
    ]
