# Generated by Django 5.2.9 on 2025-12-27 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost_incl_tax',
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom de la société'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_professional',
            field=models.BooleanField(default=False, verbose_name='Est une entreprise ?'),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° TVA Intracom.'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_tax_rate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='company.taxrate'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apartment, unit, etc.'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(max_length=255, verbose_name='Street and Number'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='free_shipping_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='relay_point_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Taux TVA (%)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_type',
            field=models.CharField(choices=[('CODE', 'Promo Code (Coupon)'), ('BRAND_OFFER', 'Brand Promotion'), ('STORE_WIDE', 'Store-wide Sale')], max_length=20),
        ),
    ]
