# Generated by Django 5.2.9 on 2025-12-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderline',
            old_name='unit_price',
            new_name='unit_price_incl_tax',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost_incl_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
    ]
