# Generated by Django 5.2.9 on 2025-12-27 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_low_stock_threshold_and_more'),
        ('sales', '0002_rename_unit_price_orderline_unit_price_incl_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expiry_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='applied_credit_note',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.creditnote'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('promo_type', models.CharField(choices=[('CODE', 'Promo Code (Coupon)'), ('BRAND_OFFER', 'Brand Promotion (Cashback/Instant)'), ('STORE_WIDE', 'Store-wide Sale')], max_length=20)),
                ('code', models.CharField(blank=True, help_text='Laisser vide pour offre automatique', max_length=50, null=True, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENT', '%'), ('FIXED', '€')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('excluded_categories', models.ManyToManyField(blank=True, related_name='excluded_from_promos', to='inventory.category')),
                ('excluded_products', models.ManyToManyField(blank=True, related_name='excluded_from_promos', to='inventory.product')),
                ('target_brands', models.ManyToManyField(blank=True, to='inventory.brand')),
                ('target_categories', models.ManyToManyField(blank=True, to='inventory.category')),
                ('target_products', models.ManyToManyField(blank=True, related_name='included_in_promos', to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='applied_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.promotion'),
        ),
    ]
