# Generated by Django 5.2.9 on 2025-12-27 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, help_text='URL friendly name', null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix HT')),
                ('retail_price_incl_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix TTC')),
                ('margin_coefficient', models.DecimalField(decimal_places=2, default=1.5, max_digits=4, verbose_name='Coeff. Marge')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name="Seuil d'alerte")),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('tax_rate', models.ForeignKey(help_text='Sélectionnez le taux de TVA pour ce produit', on_delete=django.db.models.deletion.PROTECT, to='company.taxrate', verbose_name='Taux de taxe applicable')),
            ],
        ),
    ]
