# Generated by Django 5.2.9 on 2025-12-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, verbose_name="Seuil d'alerte"),
        ),
        migrations.AddField(
            model_name='product',
            name='margin_coefficient',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=4, verbose_name='Coeff. Marge'),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price_incl_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix TTC'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock disponible'),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux TVA (%)'),
        ),
    ]
