"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+q5##m)^!a&4d)15^7x0@g5u&po+h5!zaw5o^1p@chh_xs9166'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventory.apps.InventoryConfig',
    'procurement.apps.ProcurementConfig',
    'sales.apps.SalesConfig',
    'company.apps.CompanyConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sales.context_processors.dashboard_stats', # Ton processeur de stats
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        "NAME": "oaf",
        "USER": "oaf",
        "PASSWORD": "Oo0Aa@Ff{!",
        "HOST": "db",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "OpenAxFlo",
    "site_header": "OpenAxFlo",
    "site_brand": "OpenAxFlo",
    "welcome_sign": "Bienvenue sur votre ERP OpenAxFlo",
    "copyright": "MKDEVS",
    "search_model": ["inventory.Product"], # Ajoute une barre de recherche
    "show_sidebar": True,
    "navigation_expanded": True,
    
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
    ],

    "show_sidebar": True,
    "navigation_expanded": True,

    # Organisation des menus
    "order_with_respect_to": ["inventory", "procurement", "sales", "auth"],

    "icons": {
        "auth.user": "fas fa-user-cog",
        "inventory.product": "fas fa-camera",
        "inventory.category": "fas fa-stream",
        "inventory.brand": "fas fa-copyright",
        "procurement.supplier": "fas fa-truck",
        "procurement.purchaseprice": "fas fa-tags",
        "sales.customer": "fas fa-users-tie",
        "sales.order": "fas fa-file-invoice-dollar",
        "sales.promotion": "fas fa-percentage",
        "sales.creditnote": "fas fa-hand-holding-usd",
    },

    "show_ui_builder": True, # Permet de tester les couleurs en direct
    "changeform_format": "horizontal_tabs", # Très utile pour les longs formulaires Order
}

# Optionnel : changer la couleur pour être sûr de voir le changement
JAZZMIN_UI_TWEAKS = {
    "theme": "flatly", # Un thème clair et pro
}
